### ISSUE TITLE
Why is there a proprietary "All rights reserved" footer?

### ISSUE THREAD

**Issue by mcepl** [firewalld/firewalld.github.io#3]
https://github.com/firewalld/firewalld.github.io/blob/b083879d89fa52e99279f4a75b7e943e90149852/_includes/footer.html#L4

Please, add some link to the ``LICENSE`` file to emphasize that documentation is Unlicensed. Otherwise, people could get (and [do get](https://lists.opensuse.org/opensuse-factory/2018-03/msg00277.html)) confused.

**Comment by erig0** [comment]
Thanks for the report. I agree it should be a link to LICENSE.

**Comment by jowagner** [comment]
I'm not part of the project, but wouldn't the licence file apply to the code that generates the website while the website it self (the result of rendering) may have different terms? This would make sense if the code pulls in content from outside the code repository, for example external images. Maybe also the result of automated content transformation can be newly protected. (In case of manual content transformation, I read in many places that new copyright protected can arise.)
